#!/bin/sh
set -eu

CHROOT="$(awk '$2 ~ /calamares/ && $2 ~ /\/proc$/ {sub(/\/proc$/, "", $2); print $2; exit}' /proc/mounts)"
if [ -z "$CHROOT" ]; then
    echo "Unable to determine Calamares target mount point" >&2
    exit 1
fi

if awk -v target="$CHROOT" '$2 == target && $1 ~ /^\/dev\/mapper\/luks/ { found=1 } END { exit(found ? 0 : 1) }' /proc/mounts; then
    echo "UMASK=0077" > "$CHROOT/etc/initramfs-tools/conf.d/initramfs-permissions"
    DEBIAN_FRONTEND=noninteractive chroot "$CHROOT" apt-get -y install cryptsetup-initramfs cryptsetup keyutils
fi

if [ -d /sys/firmware/efi/efivars ]; then
    DEBIAN_FRONTEND=noninteractive chroot "$CHROOT" apt-get -y install shim-signed grub-efi-amd64-signed
else
    DEBIAN_FRONTEND=noninteractive chroot "$CHROOT" apt-get -y install grub-pc
fi

if [ -x "$CHROOT/usr/sbin/update-grub" ]; then
    chroot "$CHROOT" /usr/sbin/update-grub
fi
