# Configuration file for Calamares
# Derived from Debian calamares-settings-debian
# Syntax is YAML 1.2
---
modules-search: [ local, /usr/lib/calamares/modules ]

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - sentia-cleanup-live
      - luksbootkeyfile
      - dpkg-unsafe-io
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - bootloader-config
      - grubcfg
      - bootloader
      - packages
      - plymouthcfg
      - initramfscfg
      - initramfs
      - dpkg-unsafe-io-undo
      - sources-final
      - umount
  - show:
      - finished

branding: sentia
prompt-install: false
dont-chroot: false
