#!/usr/bin/env bash
set -euo pipefail

lb config noauto \
  --mode debian \
  --architectures amd64 \
  --distribution trixie \
  --archive-areas "main non-free-firmware" \
  --binary-images iso-hybrid \
  --debian-installer none \
  --mirror-bootstrap https://deb.debian.org/debian \
  --mirror-chroot https://deb.debian.org/debian \
  --mirror-chroot-security https://deb.debian.org/debian-security \
  --mirror-binary https://deb.debian.org/debian \
  --mirror-binary-security https://deb.debian.org/debian-security \
  --security true \
  --updates true \
  --checksums sha256 \
  --chroot-squashfs-compression-type zstd \
  --chroot-squashfs-compression-level 15 \
  --iso-application "Sentia Linux" \
  --iso-publisher "Sentia Linux" \
  --iso-volume "Sentia 0.1 amd64" \
  --bootappend-live "boot=live components console=tty0 console=ttyS0,115200 live-config.hostname=sentia"
