#!/bin/sh
set -eu

if command -v sentia-terminal >/dev/null 2>&1; then
    exec sentia-terminal "$@"
fi

if command -v xfce4-terminal >/dev/null 2>&1; then
    exec xfce4-terminal "$@"
fi

if command -v x-terminal-emulator >/dev/null 2>&1; then
    exec x-terminal-emulator "$@"
fi

if command -v xterm >/dev/null 2>&1; then
    exec xterm "$@"
fi

exit 0
