# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
efi:
  mountPoint: "/boot/efi"
  recommendedSize: 512MiB
  minimumSize: 300MiB
  label: "EFI"

userSwapChoices:
  - file

initialSwapChoice: file
luksGeneration: luks2
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none

defaultPartitionTableType: gpt
requiredPartitionTableType: gpt

defaultFileSystemType: "ext4"
availableFileSystemTypes: [ "ext4" ]

essentialMounts: [ "live-*", "control", "ventoy" ]

lvm:
  enable: false

requiredStorage: 20
